services:
  - type: web
    name: persona-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        value: ${GEMINI_API_KEY}
    plan: free
    autoDeploy: true